[infomation]
name = "misc"
description = "Misc utils"

[install]
apt = ["patchelf", "psmisc", "tree", "make"]

[install.alias]
needed = "patchelf --print-needed"
make="cmd_dur make"

[install.command]

needed_r = """
#!/bin/bash

_do_print(){
    test -f $1 || return -1
    for dep in $(patchelf --print-needed $1); do
        echo $dep
        test -f $dep &&  _do_print $dep
    done
}

needed_r(){
    results=$(_do_print $1  | sort | uniq)
    for result in ${results[@]}; do
        echo $result
    done
}

needed_r $@
"""

cmd_dur = """
#!/bin/bash

cmd_dur() {
    local  start end elapsed
    start=$(date +%s.%N)
    $@
    end=$(date +%s.%N)

    elapsed=$(echo "$end - $start" | bc -l)

    echo "Command executed: $*"
    echo "start： $(date -d "@$start" +"%Y-%m-%d %H:%M:%S")"
    echo "end： $(date -d "@$end" +"%Y-%m-%d %H:%M:%S")"
    echo "elapsed: ${elapsed} seconds"
}

cmd_dur $@
"""