[infomation]
name = "rust"
description = "Rust development utils"

[install.alias]
cargo = "fix_cargo"
cargo-fix = "cargo fix --allow-dirty && cargo fmt"

[install.command]
fix_cargo = """
#!/bin/bash
set -- "${@/-E/--example}"
set -- "${@/-A/--all}"
cargo $@
"""

[install.env]
RUST_LOG = "INFO"