name: Release

on:
  workflow_dispatch:

env:
  CC: clang

jobs:
  build_installer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "littrick/littrailblazer"

      - uses: actions/checkout@v4
        with:
          path: configs

      - name: Setup the toolchain
        run: rustup default nightly

      - name: Setup the target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Check the config files
        run: cargo r --bin checker -- configs/*.toml

      - name: Build the Installer
        run: cargo r --bin installer_builder -- pioneer -c configs/*.toml

      - uses: actions/upload-artifact@v4
        with:
          name: installer
          path: installer.sh
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build_installer

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: installer

      - name: Release with tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          body: |
            Install it
            ```sh
            curl -L https://github.com/littrick/installer.sh/releases/download/${{ github.sha }}/installer.sh | bash
            ```
          files: installer.sh
